ALTER TABLE application_user
ALTER COLUMN lockout_end TYPE TIMESTAMPTZ,
ALTER COLUMN created_on TYPE TIMESTAMPTZ,
ALTER COLUMN last_modified_on TYPE TIMESTAMPTZ;

ALTER TABLE application_role
ALTER COLUMN created_on TYPE TIMESTAMPTZ,
ALTER COLUMN last_modified_on TYPE TIMESTAMPTZ;

ALTER TABLE persisted_grant
ALTER COLUMN consumed_time TYPE TIMESTAMPTZ,
ALTER COLUMN create_time TYPE TIMESTAMPTZ,
ALTER COLUMN expiration TYPE TIMESTAMPTZ;